### ISSUE TITLE
v0.7.0

### ISSUE THREAD

**Issue by bmewburn** [bmewburn/intelephense#17]
The goal of v0.7.0 is to address the below issues and clean up the code to get it into a state where it's easier to contribute and develop. I'll open up the project to contributions after this. There's still many features and improvements to be done and would be great to get some help.

- [x] magic method completion #13 
- [x] formatting #3 
- [x] symbol caching #5 
- [x] define() #18 
- [x] use declaration upon completion #20 
- [x] type resolve ?? #32 
- [x] php docblocker conflict #30 
- [x] doc selector scheme #34

**Comment by magbicaleman** [comment]
Would like to add: [Null coalescing operator](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op)

**Comment by romainp89** [comment]
When do you plan to deploy this new version?

**Comment by bmewburn** [comment]
I'll publish on Friday 23 June. It's mostly done, I'm just debugging
