### ISSUE TITLE
v0.8.0

### ISSUE THREAD

**Issue by bmewburn** [bmewburn/intelephense#35]
The focus of v0.8.0 is reference provider functionality, the additional issues below, and to continue refactoring and optimising code.

- [x] references #7 
- [x] symbol lookup refactor #26 
- [x] multiple locations for go to #28 
- [x] type resolution refactor #25 
- [x] closure completions #39 
- [x] define const go to #41 
- [x] cleanup add use decl. command and add setting to enable automatic use decl. on completion #44 bmewburn/vscode-intelephense#15
- [x] fix extra lines being inserted by format when a comment precedes a close brace bmewburn/vscode-intelephense#18

**Comment by bmewburn** [comment]
released
